name: 'Build new release after merge PR'

on:
  pull_request:
    branches:
      - develop

jobs:
  release:
    name: 'Create release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Create release'
#        uses: zendesk/action-create-release@v1
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
