name: 'Build new release after merge PR'

on:
  pull_request:
    branches:
      - develop

jobs:
  release:
    name: 'Create release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3

      - name: 'Create release'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }
          release_name: ${{ steps.changelog.outputs.tag }
          body: ${{ steps.changelog.outputs.clean_changelog }

#      - name: 'Create release'
#        uses: zendesk/action-create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
