name: 'Build new release after merge PR'

on:
  pull_request:
    branches:
      - develop

jobs:
  release:
    name: 'Create release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
